### ISSUE TITLE
No bower.json present

### ISSUE THREAD

**Issue by iamchriswick** [mhulse/grunt-html-boiler#35]
In your instruction you say that one can optionally, install the latest Bower plugin versions via `$ grunt bower` and that this this will install plugins (as defined in source/bower.json) into the source/files/plugins/ directory.

I can't seem to find either the source directory or a bower.json present in this repository...

**Comment by mhulse** [comment]
Ah, thanks for pointing that out!

At one point I was using `source` as the folder used to contain build files; I eventually changed that to `build` … Reasoning: I like to use `source` in the `images` folder (where I put source `psd` or `ai` files) and I thought it made more sense to not use the term `source` in multiple contexts.

Anyway, let me update my docs; sorry for the confusion. Thanks again for pointing this out. :+1:

**Comment by mhulse** [comment]
Updated. Thanks again for the notice. Let me know if you notice any other issues. :+1:

**Comment by iamchriswick** [comment]
No worries! :)

But, the name _"build"_ confused me a bit, cause for me build sounds like something that has been built.

Maybe like this:

grunt-html-boiler
├── build
│   ├── dev
│   │   ├── images
│   │   ...
│   ├── prod
│   │   ├── 1.0.0
│   │   ...
├── work
│   ├── files
│   │   ├── .jshintrc
│   │   ├── Gruntfile.js
│   │   ├── README.md
│   │   ├── bower.json
│   │   ├── README
│   │   └── package.json
│   .editorconfig
│   .gitattributes
│   .gitignore
│   file001.txt  
│   CONTRIBUTING.md
│   LICENSE
│   README.md
│   index.html

**Comment by mhulse** [comment]
Great points and advice. Let me open a new issue and I'll move your idea there so it can be discussed further. :)

**Comment by mhulse** [comment]
Moved to: #42

**Comment by iamchriswick** [comment]
:+1:
