### ISSUE TITLE
Errors on $ grunt

### ISSUE THREAD

**Issue by iamchriswick** [mhulse/grunt-html-boiler#36]
Running `$ grunt` out of the box results in the following error:

Running "jshint:init" (jshint) task

   ./Gruntfile.js
     56 |                     ' _/\n\n',
                                       ^ Extra comma. (it breaks older versions of IE)
     93 |                    verbose: true,                // Debug output.
                                          ^ Extra comma. (it breaks older versions of IE)
     95 |                },
                          ^ Extra comma. (it breaks older versions of IE)
     97 |            },
                      ^ Extra comma. (it breaks older versions of IE)
    117 |                './files/templates/__/_',
                                                 ^ Extra comma. (it breaks older versions of IE)
    121 |            tasks: ['default'],
                                       ^ Extra comma. (it breaks older versions of IE)
    138 |                jshintrc: '.jshintrc', // Defined options and globals.
                                              ^ Extra comma. (it breaks older versions of IE)
    145 |                './files/scripts/<%= pkg.name %>._.js',
                                                               ^ Extra comma. (it breaks older versions of IE)
    147 |            ],
                      ^ Extra comma. (it breaks older versions of IE)
    163 |                NODE_ENV: 'DEVELOPMENT',
                                                ^ Extra comma. (it breaks older versions of IE)
    169 |                NODE_ENV: 'PRODUCTION',
                                               ^ Extra comma. (it breaks older versions of IE)
    171 |            },
                      ^ Extra comma. (it breaks older versions of IE)
    187 |                force: true, // Allows for deletion of folders outside current working dir (CWD). Use with caution.
                                    ^ Extra comma. (it breaks older versions of IE)
    193 |                '../dev/__/_',
                                      ^ Extra comma. (it breaks older versions of IE)
    200 |                '../index.html',
                                        ^ Extra comma. (it breaks older versions of IE)
    202 |            ],
                      ^ Extra comma. (it breaks older versions of IE)
    221 |                    banner: '<%= banner.short %>',
                                                          ^ Extra comma. (it breaks older versions of IE)
    233 |                        './files/scripts/<%= pkg.name %>.init.js',
                                                                          ^ Extra comma. (it breaks older versions of IE)
    234 |                    ],
                              ^ Extra comma. (it breaks older versions of IE)
    238 |                },
                          ^ Extra comma. (it breaks older versions of IE)
    240 |            },
                      ^ Extra comma. (it breaks older versions of IE)
    259 |                sourcemap: 'none', // Generate CSS source maps?
                                          ^ Extra comma. (it breaks older versions of IE)
    268 |                    style: 'expanded', // Output style. Can be nested, compact, compressed, expanded.
                                              ^ Extra comma. (it breaks older versions of IE)
    275 |                    '../dev/styles/development.css': './files/styles/development.scss',
                                                                                               ^ Extra comma. (it breaks older versions of IE)
    277 |                },
                          ^ Extra comma. (it breaks older versions of IE)
    286 |                    style: 'compressed',
                                                ^ Extra comma. (it breaks older versions of IE)
    292 |                    '../prod/<%= pkg.version %>/<%= now %>/<%= ver %>/styles/<%= pkg.name %>.min.css': './files/styles/<%= pkg.name %>.scss',
                                                                                                                                                     ^ Extra comma. (it breaks older versions of IE)
    294 |                },
                          ^ Extra comma. (it breaks older versions of IE)
    296 |            },
                      ^ Extra comma. (it breaks older versions of IE)
    324 |                    version: '<%= pkg.version %>',
                                                          ^ Extra comma. (it breaks older versions of IE)
    326 |                },
                          ^ Extra comma. (it breaks older versions of IE)
    341 |                            '!latest.html',
                                                   ^ Extra comma. (it breaks older versions of IE)
    343 |                        dest: '../dev/',
                                                ^ Extra comma. (it breaks older versions of IE)
    345 |                    },
                              ^ Extra comma. (it breaks older versions of IE)
    347 |                ],
                          ^ Extra comma. (it breaks older versions of IE)
    360 |                            'index.html',
                                                 ^ Extra comma. (it breaks older versions of IE)
    362 |                        dest: '../prod/<%= pkg.version %>/<%= now %>/<%= ver %>/',
                                                                                          ^ Extra comma. (it breaks older versions of IE)
    367 |                        dest: '../prod/index.html',
                                                           ^ Extra comma. (it breaks older versions of IE)
    369 |                    },
                              ^ Extra comma. (it breaks older versions of IE)
    371 |                ],
                          ^ Extra comma. (it breaks older versions of IE)
    373 |            },
                      ^ Extra comma. (it breaks older versions of IE)
    399 |                            '!**/source/**',
                                                    ^ Extra comma. (it breaks older versions of IE)
    401 |                        dest: '../dev/',
                                                ^ Extra comma. (it breaks older versions of IE)
    403 |                    },
                              ^ Extra comma. (it breaks older versions of IE)
    405 |                ],
                          ^ Extra comma. (it breaks older versions of IE)
    420 |                            '!**/junk/**',
                                                  ^ Extra comma. (it breaks older versions of IE)
    422 |                        dest: '../prod/<%= pkg.version %>/<%= now %>/<%= ver %>/',
                                                                                          ^ Extra comma. (it breaks older versions of IE)
    428 |                        dest: '../index.html',
                                                      ^ Extra comma. (it breaks older versions of IE)
    430 |                    },
                              ^ Extra comma. (it breaks older versions of IE)
    434 |                ],
                          ^ Extra comma. (it breaks older versions of IE)

> > Too many errors. (90% scanned).
> > 
> > 51 errors in 5 files

**Comment by mhulse** [comment]
Ah, there might have been a change to how grunt handles things since I last tested my code. Fortunately, it all looks pretty easy to fix. I'll post an update to my code today.

Thanks for your report! Sorry for the inconvenience.

**Comment by mhulse** [comment]
> there might have been a change to how grunt handles things since I last tested my code

... and/or `jshint`. Working on this now. Will have it fixed up here shortly.

**Comment by mhulse** [comment]
Ok, should be fixed.

If you run into more issues, don't hesitate to open a new issue(s).

Thanks! :octocat:
